# Generated by Django 6.0.6 on 2026-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
