# Generated by Django 6.0.6 on 2026-06-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userdetail_business_name_userdetail_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
