# Generated by Django 6.0.6 on 2026-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userdetail_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash On Delivery')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
